version: '3'

networks:
  backend:
    external: true

services:
  portainer:
    build:
      context: ./portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DATA_PATH_HOST}/portainer_data:/data
    ports: 
      - ${PORTAINER_SERVER_PORT}:8000
      - ${PORTAINER_CLIENT_PORT}:9000
    networks:
      - backend

  nginx:
    build:
      context: ./nginx
    restart: always
    volumes:
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_PROJECTS_PATH}:/var/www
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
      # - ${NGINX_HOST_SOCKETIO_PORT}:8000
    networks:
      - backend

  # traefik:
  #     build:
  #         context: ./traefik
  #     restart: always
  #     ports:
  #         - "80:80"
  #         - "443:443"
  #     volumes:
  #         - /var/run/docker.sock:/var/run/docker.sock
  #         - ./traefik/traefik.toml:/traefik.toml
  #     labels:
  #         - "traefik.docker.network=web"
  #         - "traefik.enable=true"
  #         - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
  #     networks:
  #         - backend

  #mysql
  mysql:
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    restart: always
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - ${DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_VERSION=${MYSQL_VERSION}
      - MYSQL_PORT=${MYSQL_PORT}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ENTRYPOINT_INITDB=${MYSQL_ENTRYPOINT_INITDB}
      - TZ=${TZ}
    networks:
      - backend

  #postgres
  postgres:
    build:
      context: ./postgres
      args:
        - POSTGRES_VERSION=${POSTGRES_VERSION}
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ${DATA_PATH_HOST}/postgres:/var/lib/postgresql/data
      - ${POSTGRES_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend

  #influxdb
  influxdb:
    build:
      context: ./influxdb
      args:
        - INFLUXDB_VERSION=${INFLUXDB_VERSION}
    restart: always
    ports:
      - ${INFLUXDB_PORT}:8086
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=${INFLUXDB_INIT_MODE}
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_INIT_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_INIT_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN}
    volumes:
      - ${DATA_PATH_HOST}/influxdb2:/var/lib/influxdb2
    networks:
      - backend

  #adminer
  adminer:
    build: ./adminer
    ports:
      - ${ADMIMER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${ADMINER_DEFAULT_SERVER}
    networks:
      - backend

  #liquibase
  liquibase:
    build :
      context: ./liquibase
      args:
        - LIQUIBASE_VERSION=${LIQUIBASE_VERSION}
    restart: always

  #minio
  minio:
    build: ./minio
    volumes:
      - ${DATA_PATH_HOST}/minio:/data
    #   - ${CONFIG_PATH_HOST}/minio:/root/.minio
    ports:
      - "${MINIO_PORT}:9000"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend

  #redis
  redis:
    build:
      context: ./redis
    restart: always
    volumes:
      - ${DATA_PATH_HOST}/redis:/data
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend
  #ngrok
  ngrok:
    build:
      context: ./ngrok
    ports:
      - ${NGROK_PORT}:4040
    environment:
      - NGROK_AUTH=${NGROK_AUTH}
      - NGROK_PROTOCOL=http
      - NGROK_REGION=ap
      - NGROK_PORT=nginx:80
    depends_on:
      - nginx
    networks:
      - backend

  #cloudflared
  cloudflared:
    build:
      context: ./cloudflared
    restart: always
    volumes:
      - ./cloudflared/.cloudflared:/etc/cloudflared
    command:
        - tunnel
        - run
    networks:
      - backend

  zookeeper:
    build:
      context: ./zookeeper
    ports:
      - ${ZOOKEEPER_PORT}:2181
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    build:
      context: ./kafka
    ports:
      - ${KAFKA_PORT}:9092
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper