version: '3'

services:
    nginx:
        build:
            context: ./nginx
        restart: always
        volumes:
            - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
            - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
            - ${NGINX_SSL_PATH}:/etc/nginx/ssl
        ports:
            - "${NGINX_HOST_HTTP_PORT}:80"
            - "${NGINX_HOST_HTTPS_PORT}:443"
            - "${NGINX_HOST_SOCKETIO_PORT}:8000"
        networks:
            - backend
    # traefik:
    #     build:
    #         context: ./traefik
    #     restart: always
    #     ports:
    #         - "80:80"
    #         - "443:443"
    #     volumes:
    #         - /var/run/docker.sock:/var/run/docker.sock
    #         - ./traefik/traefik.toml:/traefik.toml
    #     labels:
    #         - "traefik.docker.network=web"
    #         - "traefik.enable=true"
    #         - "traefik.http.routers.traefik.rule=Host(`traefik.localhost`)"
    #     networks:
    #         - backend
networks:
    backend:
        external: true